In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
data = pd.read_excel('D:\sistem cerdas\studi kasus.xls')

In [17]:
data

   Unnamed: 0 Unnamed: 1  Unnamed: 2  Unnamed: 3 Unnamed: 4 Unnamed: 5
0    Kejadian      Cuaca  Temperatur  Kelembaban   Berangin    Bermain
1          K1    Berawan       Panas      Tinggi      Tidak         Ya
2          K2    Berawan      Dingin      Normal         Ya         Ya
3          K3    Berawan      Hangat      Tinggi         Ya         Ya
4          K4    Berawan       Panas      Normal      Tidak         Ya
5          K5      Hujan      Hangat      Tinggi      Tidak         Ya
6          K6      Hujan      Dingin      Normal      Tidak         Ya
7          K7      Hujan      Dingin      Normal         Ya      Tidak
8          K8      Hujan      Hangat      Normal      Tidak         Ya
9          K9      Hujan      Hangat      Tinggi         Ya      Tidak
10        K10      Cerah       Panas      Tinggi      Tidak      Tidak
11        K11      Cerah       Panas      Tinggi         Ya      Tidak
12        K12      Cerah      Hangat      Tinggi      Tidak      Tidak
13        K13      Cerah      Dingin      Normal      Tidak         Ya
14        K14      Cerah      Hangat      Normal         Ya         Ya

In [18]:
data.shape

(15, 6)

In [32]:
data['Bermain'].value_counts()

KeyError: 'Bermain'